### ISSUE TITLE
Installer should provide option to launch at startup

### ISSUE THREAD

**Issue by spundot** [MetaFight/PowerBuddy#1]
After installing, it wasn't clear whether the app would automatically launch at startup or if I needed to manually add it to the Startup directory.

It would be convenient to provide this as an installer option. (btw cool utility!)

**Comment by MetaFight** [comment]
Hi spundot.  Thanks for your feedback.  You're absolutely right, the install process is less than clear.  I'll be honest, I kind of rushed it :)

I'll try to set some time aside soon to remedy this.  Thanks!

**Comment by N8endo** [comment]
I just found this app and I love the simple interface.  I too would be very happy if you could make it launch at startup.  I hope you're still working on this.  Thanks!
