### ISSUE TITLE
Installer: NSIS installer "Start with Windows" functionality is detected as a Trojan by Windows Defender

### ISSUE THREAD

**Issue by MetaFight** [MetaFight/PowerBuddy#12]
See comments:

* https://superuser.com/questions/160866/how-do-i-display-all-power-plans-in-windows-7-notification-area/713169?noredirect=1#comment1752748_713169
* https://superuser.com/review/suggested-edits/649224
* https://superuser.com/questions/957500/easy-way-to-switch-power-plan-in-windows-10/958479#958479

The NSIS functionality probably writes to the registry "Run" key.  I'm assuming this is frowned upon nowadays leading to Windows Defender reporting it as a Trojan.

I'll find a more modern/sensible way of doing this.

**Comment by MetaFight** [comment]
I can't seem to reproduce this.  I'm hoping the person who raised the problem will come back and provide some more details.

**Comment by ujell** [comment]
Not sure if this helps, but Windows Defender identifies the trojan as [this](https://www.microsoft.com/security/portal/threat/encyclopedia/Entry.aspx?Name=Trojan:Win32/Varpes.I!cl). I just downloaded latest release directly from Releases page, wasn't even able to run the .exe

**Comment by MetaFight** [comment]
@ujell thanks, that does help.  I'm going to pull the last release until I can figure this out.

Cheers.

**Comment by MetaFight** [comment]
@ujell out of curiosity, could you share your OS version and Windows Defender "threat definition version"?  I still can't seem to reproduce this issue.

**Comment by ujell** [comment]
@MetaFight 
Windows 10 Pro, Version 1703, Build 15063.138 
If thread definition version is the same with Antivirus/Antispyware version then 1.241.890.0

**Comment by MetaFight** [comment]
@ujell  Thanks.

I'm on a slightly more recent build of Windows 10 than your, however we have the same Windows Defender version.

I've scanned the 1.2.0.0 and 1.3.0.0 builds and they report as clean.  I'm confused :|

Anyway, I just built 1.3.0.1 removing the "Start automatically with Windows" thing from the installer.  Hopefully that will help.

Could you give it a try?

https://github.com/PerfectlyCromulentLtd/PowerBuddy/releases/tag/1.3.0.1

**Comment by ujell** [comment]
@MetaFight  Seems like it works! Windows Defender didn't automatically warned me so I also manually scanned the file, no threads found.

**Comment by MetaFight** [comment]
@ujell thanks!

**Comment by MetaFight** [comment]
Resolved by 941a843

**Comment by MetaFight** [comment]
Resolved by 941a843
