### ISSUE TITLE
Edges of start menu icons are messed up

### ISSUE THREAD

**Issue by spundot** [MetaFight/PowerBuddy#2]
Not a big deal since most people will only see the systray icon (which looks okay), but the edges of the Start menu icons look really jagged.

![image](https://cloud.githubusercontent.com/assets/3210002/12083790/70a64c72-b25e-11e5-8ae7-11f05b9df1f8.png)

![image](https://cloud.githubusercontent.com/assets/3210002/12083797/845f2de2-b25e-11e5-9c75-17c65814e95d.png)

**Comment by MetaFight** [comment]
Yeah, the icons were very rushed.  I've been meaning to fix this for over a year now.  Thanks for reporting it though.  Hopefully it'll be enough motivation!

**Comment by MetaFight** [comment]
Sorry for taking so long to look at this.  Can you tell me which version of Windows you're using?  I'm having a hard time reproducing this in Windows 10, though I remember it happening to me as well in an earlier version.

If you can confirm a version of windows where this happens I'll spin up a VM to try and fix this.

Cheers.

**Comment by spundot** [comment]
Greetings, this was on Windows 7 SP1.

**Comment by FSund** [comment]
The icon is looking much better now. 

The biggest issue for me was the systray icon, which now looks very good:
![image](https://cloud.githubusercontent.com/assets/3352483/22097226/455fe502-de20-11e6-9f23-77a8c32bd041.png)

The start menu icon also looks good
![image](https://cloud.githubusercontent.com/assets/3352483/22097240/560951cc-de20-11e6-8a8a-cf0d6d9baa61.png)

But the icon I get when I search for Power Buddy still looks a bit rough. Could this be a left over icon from an older version?
![image](https://cloud.githubusercontent.com/assets/3352483/22097245/5f01ba12-de20-11e6-9ab1-13406de884d9.png)

**Comment by MetaFight** [comment]
I had the same thing. I had to manually delete my windows icon cache and reboot before it changed.

I double checked the installer and binaries too. They don't have the old icon anymore so this is definitely a windows issue.

I'll see if I can get the installer to automatically invalidate the cache.
