### ISSUE TITLE
The icon

### ISSUE THREAD

**Issue by spin360** [MetaFight/PowerBuddy#4]
As someone else mentioned, here is "another guy to motivate you" lol

The icon looks like trash.

I just installed the app and I like it very much, it's simple and does what it's good for. If you have no time for that, maybe I can make the icon if you send me your original sized one. I suck at photoshop though, so  it might take quite a while...

**Comment by MetaFight** [comment]
Thanks for the bump.  I'm going to try and get the icon issue sorted out in the next few days.

(Closing this item as a duplicate of #2 )
